[#37] 바텀네비게이션 제작
SCBJ-7/SCBJ-FE pull request #42
Opened 2024-01-04 11:38 UTC by Bumang-Cyber

### Issue Number

close https://github.com/SCBJ-7/SCBJ-FE/issues/37

### ⛳️ Task

- [x] 화이팅하기
- [x] 바텀네비게이션 퍼블리싱
- [x] 바텀네비게이션 라우팅
- [x] NavLink의 isActive를 이용하여 선택된 버튼 primary컬러 설정

### ✍️ Note

## 1. 컴포넌트 폴더에 BottomNav 추가

App.tsx에 추가해놓았습니다.

```javascript
function App() {
  return (
    <S.Container>
      {/* <SHeader /> */}
      <S.Wrapper>
        <Outlet />
      </S.Wrapper>
      <BottomNav /> // 바텀 네비게이션
    </S.Container>
  );
}
```

<br>
<br>
<br>

## 2. 아이콘은 react-icon을 스타일드컴포넌트로 변환하여 사용

스타일드컴포넌트에 react-icon을 불러와 크기 조정하고 S.NavIcon...으로 바꿔서 썼습니다.
그러나 홈 아이콘은 react-icon이 아니라 지은님께서 따로 만드신 아이콘이기 때문에 따로 svg를 써야했습니다.

<br>
<br>
<br>

## 3. svg를 리액트 컴포넌트로 변경해서 사용

네비게이션 아이콘들은 포커스될 시 아래 로직으로 색상 변경을 시켜줍니다.

```javascript
export const BottomNavCell = styled(NavLink)`
  width: 25%;
  height: 100%;

  display: flex;
  flex-direction: column;
  margin-top: 10px;
  align-items: center;
  gap: 2px;

  ${typo.caption3}

  color: white;
  &.active {
    color: ${({ theme }) => theme.color.primary}; // 선택 시 primary 컬러로 변경
  }
`;
```

하지만 홈아이콘 svg파일이라 스타일드 컴포넌트로 다룰 수 없었습니다. (찾아본 스타일드 컴포넌트가 svg를 읽을 수 없는거 같습니다..)
동적으로 색상을 변경시켜야하는데 스타일드 컴포넌트를 못 쓰길래 차라리 svg를 리액트 컴포넌트로 변환하여 사용했습니다.
[참고링크]( https://velog.io/@ubin_ing/svg%EB%A5%BC-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EB%A1%9C-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%84%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90)

```javascript
// 예시
const NavIconHome = ({ isActive }: { isActive: boolean }) => {
  return (
    <svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" fill="none">
      <g clipPath="url(#clip0_1724_9234)">
        <path
          d="M26.4873 ..."
          fill={isActive ? theme.color.primary : "white"} // isActive면 프라이머리 컬러, 아니면 흰색
        />
```

<br>
그리고, BottomNav.tsx에서 useLocation을 활용하여 path가 PATH.ROOT인 경우 
홈아이콘에 isActive: true를 주게되어 아이콘 색상이 바뀌게 했습니다.

### 📸 Screenshot

https://github.com/SCBJ-7/SCBJ-FE/assets/126222848/46e86a15-4952-43bf-8288-d62d9ce5e61e

### 📎 Reference

2024-01-04 13:18 UTC, wowba requested changes

2024-01-04 13:18 UTC, wowba commented on src/App.tsx
> +import BottomNav from "./components/bottomNav";
경로 문제가 있는 것 같습니다. 확인 부탁드려요!

https://github.com/SCBJ-7/SCBJ-FE/actions/runs/7409018666/job/20158397480

2024-01-04 13:18 UTC, wowba commented on src/assets/icons/NavHome.tsx
> +export default NavIconHome;
ReactComponent를 이용해 svg 파일을 컴포넌트로 변환한 뒤, 스타일드 컴포넌트를 적용할 수 있습니다.

예전에 사용해 본 방법인데, 아래처럼 사용할 수 있습니다. 혹시 도움이 될 수도 있을듯 하여 남겨봅니다!
```
import { ReactComponent as loginLogo } from "../../assets/logo/loginLogo.svg";
...
const LoginLogo = styled(loginLogo)`
  width: 28rem;
`;
```

https://github.com/wowba/Calit/blob/main/src/pages/LoginPage/Login.tsx

2024-01-04 13:18 UTC, wowba commented on src/components/BottomNav/index.tsx
> +  const location = useLocation();
```suggestion
  const { pathname } = useLocation();
```
useLocation 훅에서 pathname만 사용하신다면 이렇게 해도 될 것 같습니다!

2024-01-04 13:18 UTC, wowba commented on src/components/BottomNav/index.tsx
> +    { id: 1, name: "홈", path: PATH.ROOT, icon: <S.NavIconHomes isActive={location.pathname === PATH.ROOT ? true : false} /> },
```suggestion
    { id: 1, name: "홈", path: PATH.ROOT, icon: <S.NavIconHomes isActive={pathname === PATH.ROOT ? true : false} /> },
```
위를 변경한다면 아래도 이렇게 바뀔 것 같네요

2024-01-04 14:50 UTC, Bumang-Cyber commented on src/components/BottomNav/index.tsx
> +    { id: 1, name: "홈", path: PATH.ROOT, icon: <S.NavIconHomes isActive={location.pathname === PATH.ROOT ? true : false} /> },
넵 간소화해보도록 하겠습니다!

2024-01-04 15:26 UTC, Bumang-Cyber commented on src/assets/icons/NavHome.tsx
> +export default NavIconHome;
알려주신 방법을 시도해보고 있었는데 vite에선 해당 방식이 또 안 되네요 ㅠㅠ
npm install vite-plugin-svgr 이란 라이브러리를 설치해야 된다고 합니다.
https://dev.to/cassidoo/importing-svg-files-as-react-components-with-vite-l3n

2024-01-04 15:46 UTC, Bumang-Cyber commented on src/assets/icons/NavHome.tsx
> +export default NavIconHome;
Uncaught SyntaxError: The requested module '/src/assets/icons/NavHomeIcon.svg?import' does not provide an export named 'ReactComponent' (at bottomNav.styled.tsx:10:10)
계속 이런 에러가 뜹니다ㅠㅠ
영욱님께선 vite환경에서도 import { ReactComponent as Svgname } from "..."을 하셨던 걸까요?

일단 지금처럼 
<img width="313" alt="image" src="https://github.com/SCBJ-7/SCBJ-FE/assets/126222848/8fd82396-db39-4567-a756-4ba791380932">
svg를 실제 컴포넌트로 만들어서 import하는 방식으로 진행하겠습니다!

2024-01-04 15:50 UTC, wowba commented on src/assets/icons/NavHome.tsx
> +export default NavIconHome;
혹시 이 글 참고해보시겠어요?

https://stackoverflow.com/questions/70309561/unable-to-import-svg-with-vite-as-reactcomponent

2024-01-04 15:52 UTC, Bumang-Cyber commented
영욱님이 말씀하신 경로문제와 pathname 구조분해할당으로 꺼내오는거는 해결했습니다!

그런데 import {ReactComponent as BlarBlar} from "./blarblar.svg"로 SVG 불러오는거는 계속 아래 에러가 뜨고 실패하네요.

Uncaught SyntaxError: The requested module '/src/assets/icons/NavHomeIcon.svg?import' does not provide an export named 'ReactComponent' (at bottomNav.styled.tsx:10:10)

일단은 되는 방식으로 해보겠습니다!

2024-01-04 15:52 UTC, wowba commented on src/assets/icons/NavHome.tsx
> +export default NavIconHome;
vite 환경에서 제가 예전에 작업한 코드입니다! 전에 드렸던 방법은 CRA에서 활용한 방법이네요

https://github.com/Mini-Team-6/Mini-Team-6-Frontend/blob/main/src/components/Header/Header.tsx

2024-01-04 15:55 UTC, Bumang-Cyber commented on src/components/BottomNav/index.tsx
> +  const location = useLocation();
넵 수정하였습니다. 그런데 여기서 Commit suggestion 버튼만 눌러도 수정이 되는거 같군요! 신기합니다ㅋㅋ

2024-01-04 15:57 UTC, wowba commented
> 영욱님이 말씀하신 경로문제와 pathname 구조분해할당으로 꺼내오는거는 해결했습니다!
> 
> 그런데 import {ReactComponent as BlarBlar} from "./blarblar.svg"로 SVG 불러오는거는 계속 아래 에러가 뜨고 실패하네요.
> 
> Uncaught SyntaxError: The requested module '/src/assets/icons/NavHomeIcon.svg?import' does not provide an export named 'ReactComponent' (at bottomNav.styled.tsx:10:10)
> 
> 일단은 되는 방식으로 해보겠습니다!

예전에 작업한 내용을 확인해보니 "vite-plugin-svgr": "^4.2.0" 은 devDependency로 설치하고,
아래처럼 svg 파일을 임포트에 스타일드 컴포넌트를 적용했네요

```
import HeaderLogo from "../../assets/logo/headerLogo.svg?react";
...
const HeaderLogoSVG = styled(HeaderLogo)`
  fill: ${({ theme }) => theme.Color.mainColor};
  margin: 0 0 0 0.25rem;
`;
```

2024-01-04 16:13 UTC, Bumang-Cyber commented
>예전에 작업한 내용을 확인해보니 "vite-plugin-svgr": "^4.2.0" 은 devDependency로 설치하고,
아래처럼 svg 파일을 임포트에 스타일드 컴포넌트를 적용했네요

넵! svgr 플러그인을 깔면 불러와진다해서 깔아서 해봤는데 import는 되네요!
그런데 NavLink의 isActive값에 따라 동적으로 아이콘에 스타일 할당해보려했는데
fill값이 원하는대로 바뀌진 않는거 같습니다. 
어차피 제가 생각했던 방법이 안 통하니 svgr도 지우고 일단 기존대로 해보겠습니당!

그래도 정말 좋은 꿀팁 많이 주셔서 감사합니다!! 참고가 되었어요!

2024-01-05 02:20 UTC, im-na0 reviewed
수고하셨습니다~!!! 네비바 짱 이뻐요

2024-01-05 02:20 UTC, im-na0 commented on src/components/navBottom/index.tsx
> +              className={(isActive) => (isActive ? "active" : "")}
오옹 NavLink 컴포넌트는 처음 알았는데
activeClassName 를 사용하면 현재 URL과 to가 가리키는 링크가 일치할 때, activeClassName이 활성화된다네요

activeClassName 속성활용하시면 더 좋을 것 같아요!

https://velog.io/@seong-dodo/React-Link%EC%99%80-NavLink#-%ED%8A%B9%EC%A0%95-%EB%A7%81%ED%81%AC%EC%97%90-%EC%8A%A4%ED%83%80%EC%9D%BC%EC%9D%84-%EB%84%A3%EC%96%B4%EC%A3%BC%EB%8A%94-navlink

2024-01-05 02:20 UTC, im-na0 commented on src/components/navBottom/bottomNav.styled.tsx
스타일 파일은 객체를 반환해서 tsx보다 ts가 더 맞는 것 같습니다!

그나저나 저희 style 파일은 styled 통일했었나요? 그리고 저희 폴더명이나 파일명이 파스칼 / 카멜 케이스가 혼재되어 있어서 헷갈리네욤 ;ㅡ; 이부분 컨벤션도 잡아보면 좋을 것 같습니다

2024-01-05 02:20 UTC, im-na0 commented on src/components/layout/index.tsx
제가 App에 있는 스타일은 layout에 관리하자고 한 건 

```typescript
Layout
ㄴ index.tsx
ㄴ Layout.style.ts
ㄴ Header
|   ㄴ Header.tsx
ㄴ Footer
|   ㄴ Footer.tsx

``` 
이런식으루 Layout/index.tsx 에서 Container와 Wrapper를 합쳐서 반환하는걸로 생각했는데 지금 구조로는 안될 것 같네요,,
🤔 이부분에 대한 다른분들의 의견도 듣고싶어요...!

그리고 이 파일은 스타일객체만 반환하고 있어서 tsx 대신 ts를 사용하는게 목적에 더 맞는 것 같습니다

2024-01-05 02:48 UTC, Bumang-Cyber commented on src/components/layout/index.tsx
나영님께서 말씀하신 구조로 하면 

App.tsx의 리턴부분은
```javascript
  return (
      <Layout>
        <OutLet />
      </Layout>
  )
```
가 되겠네여!

2024-01-05 02:52 UTC, Bumang-Cyber commented on src/components/navBottom/bottomNav.styled.tsx
넵 ts로 바꿀 수 있는 부분은 ts로 바꾸겠습니다. 그리고 .styled.를 붙이는걸로 이해하고 있었는데 다른 방법이 있었을까요?
폴더명 컨벤션도 정해봐야할거같습니다!

2024-01-05 03:07 UTC, Bumang-Cyber commented on src/components/layout/index.tsx
확실히 정리가 더 잘 되어보이는거 같아요. App.tsx에 Layout 말고도 다른 것들도 들어올 수 있을거 같으니
나영님 말씀대로 Layout컴포넌트를 한데 정리해서 App.tsx에서 정리하는게 더 나을거같네여. 바꿔서 반영해보겠습니다!

2024-01-05 03:53 UTC, chaeminseok reviewed
Nav bar만들어주셔서 감사합니다 . 전체적으로 코드가 깔끔하고 여러 배울요소들이 있네요 . 고생하셨습니다!

2024-01-05 03:54 UTC, Bumang-Cyber commented on src/components/navBottom/index.tsx
> +              className={(isActive) => (isActive ? "active" : "")}
isActive속성도 active될 때 언제든 꺼내서 쓸 수 있던데 activeClassName도 쓸 수 있군여!
저는 isActive를 styled component에 전달해서 조건 처리했습니다!

라고 하려 했는데
https://velog.io/@dy6578ekdbs/React-NavLink%EC%97%90%EC%84%9C-activeClassName%EC%9D%B4-%EC%82%AC%EB%9D%BC%EC%A1%8C%EB%8B%A4

어쩐지 에러가 나더니 activeClassName이 사라졌다고 하네요..ㅠㅠ
isActive가 대안으로 나온 것인듯 싶습니다! isActive로 className 붙여주는걸로 계속 유지할게요!

2024-01-05 04:18 UTC, im-na0 approved these changes
수정사항 확인했습니다! 그리고 상세페이지 같은 경우 네비바가 없다네용..! 이부분은 제가 작업하면서 조건부 렌더링 걸겠습니다~

2024-01-05 04:25 UTC, chaeminseok approved these changes

2024-01-05 04:25 UTC, merged