[#47] typography 파일을 theme 파일로 병합
SCBJ-7/SCBJ-FE pull request #48
Opened 2024-01-05 09:43 UTC by dbstjrals

### Issue Number

close #47 

### ⛳️ Task

- [x] 화이팅하기
- [x] typography 파일을 theme 파일로 병합

### ✍️ Note
디자인 시스템과 동일하게 line-height 값은 따로 설정하지 않았습니다.

아래와 같이 사용하면 되는데, typo 적용 시 세미콜론( ; )을 추가하지 않아도 됩니다.
(추가해도 상관은 없으나, typo 값들이 css 타입을 반환하는데 모두 세미콜론이 붙어져 있기 때문입니당)

```typescript
const styledDiv = styled.div`
  ${({ theme }) => theme.typo.title1}

  background-color: ${({ theme }) => theme.color.primaryLight};
`;
```

### 📸 Screenshot
![image](https://github.com/SCBJ-7/SCBJ-FE/assets/54929509/c5028dfc-a9ec-401f-bafa-8edaae2a5d76)

### 📎 Reference

2024-01-05 09:46 UTC, wowba commented
themeProvider에서 함수로 styled-components의 css를 리턴할 수 있을줄은 몰랐는데...
정말 좋은 방법같네요!

2024-01-05 09:47 UTC, wowba requested changes
https://github.com/SCBJ-7/SCBJ-FE/actions/runs/7420302647/job/20191420072?pr=48

경로 문제가 발생하는 것 같아요. 확인 부탁드립니다!

2024-01-05 09:58 UTC, dbstjrals commented
@wowba 수정해서 다시 올렸습니다!

2024-01-05 10:50 UTC, wowba approved these changes

2024-01-05 11:02 UTC, im-na0 approved these changes
수고하셨습니다!

2024-01-06 04:18 UTC, Bumang-Cyber approved these changes
감사합니다! 제 코드에 있는 부분도 잘 수정해주신거 짱입니다!

2024-01-06 05:12 UTC, merged